### ISSUE TITLE
DELETE doesn't seem to delete

### ISSUE THREAD

**Issue by mbrakken** [jjg/jsfs#55] opened 2015-04-29 03:09 UTC
Working against the most current version, first I POST media (image in this case) and get a 200 response. Then I DELETE that image and get back a 204 response, but the log still says `1 files stored in 1 blocks, 1 unique (100%)`. Then I POST back to the same media path and get back a 405, method not allowed: 
```
File exists at /localhost/complete-submission/artists/red-hot-chili-peppers/sad-puppy.jpg, re-POST not allowed
Result: 405
```
I think I can capture the POST failure and retry with a PUT, but it doesn't seem intuitive.

**Comment by mbrakken** [comment] 2015-04-29 03:11
I should add that I'm not currently passing any sort of access key in a header with the DELETE request, but the files are also stored publicly. I haven't yet figured out how I want to handle access to what will ultimately be publicly available assets.

**Comment by jjg** [comment] 2015-04-29 03:32
I'm pretty sure DELETE requires the access_key but I'll double-check.

**Comment by mbrakken** [comment] 2015-04-29 03:38
From the docs it seems like it does, but the 204 was confusing me.

**Comment by mbrakken** [comment] 2015-04-29 03:43
I'm also getting a 405 when attempting to PUT. I think the answer is that I need to handle access keys somehow, but I'm not sure where I should put those, especially when I'm working with unauthenticated users. I don't think I should keep them with the image details, but maybe I need to...

**Comment by jjg** [comment] 2015-04-29 13:08
Again this is by design @mbrakken  (although a case could be made that it should be an `HTTP 400` vs 405).  In either case the DELETE method should not return a 2xx code, probably should be 400 if the key is omitted.  

Public files are readable by anyone but modifiable only by the holder of the key (i.e., the "owner").

If you need to manage stored items after storing them, then the keys should be held by whatever will be managing them.  This can be non-obvious in situations with anonymous users but I think we can still figure it out.

I'm going to close this issue and open a new one to address the inconsistency in DELETE's HTTP status codes, but let me know if you want to discuss the "who has the keys" problem more, I have some thoughts by they are off-topic.

**Closed by jjg** 2015-04-29 13:08 UTC

**Comment by mbrakken** [comment] 2015-04-29 13:38
Thanks. That all sounds right. The status code ended up being the primary
issue, since it didn't match the result. I'm in progress on some app
updates to handle keys.
